### ISSUE TITLE
Document how to add custom CA certs

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-docs#33]
We should give an example of how to add a custom CA to allow for air-gap scenarios.

**Comment by agracey** [comment]
This should likely be done using the cloud-config file writing. A follow on issue would be to build a mechanism to update the certs after deployment

**Comment by ldevulder** [comment]
@agracey You mean adding a CA in the deployed cluster?

**Comment by agracey** [comment]
Adding a CA to the OS itself. This is important when airgapped as you need the cert to allow for downloading the containers for the cluster itself.

**Comment by davidcassany** [comment]
To include a custom registry mirror with a custom certificate I'd do it from the machine registration cloud-config. So any node registering to this end point would be set. I do not exactly remember what I was actually testing what I did a simiar setup (I think I was trying to test IBS builds form registry.suse.de), the certificate was functional but the mirror registry setup was not (as I was not actually testing it I did not spend time on debugging). 

I'd set a registration cloud-config to something similar to:
```yaml
spec:
  config:
    cloud-config:
      write_files:
      - path: /etc/elemental/ca_certs/custom.pem
        owner: root:root
        permissions: '0644'
        content: |
          -----BEGIN CERTIFICATE-----
          MIIG6DCCBNCgAwIBAgIBATANBgkqhkiG9w0BAQsFADCBqDELMAkGA1UEBhMCREUx
          ...
          -----END CERTIFICATE-----
      - path: /etc/rancher/k3s/registries.yaml
        owner: root:root
        permissions: '0644'
        content: |
          configs:
            registry.suse.de:
              tls:
                ca_file: /etc/elemental/ca_certs/custom.pem
```

This is mostly aiming to follow [k3s docs](https://docs.k3s.io/installation/private-registry)
