### ISSUE TITLE
Document annotations automatically added in MachineInventories

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-docs#360]
Example of automatically filled in annotations:
```yaml
- apiVersion: elemental.cattle.io/v1beta1    
  kind: MachineInventory
  metadata:                                                                                                           
    annotations:
      elemental.cattle.io/auth: tpm
      elemental.cattle.io/os.cpe-name: cpe:/o:suse:sl-micro:6.0
      elemental.cattle.io/os.id: sl-micro
      elemental.cattle.io/os.image: registry.opensuse.org/isv/rancher/elemental/staging/containers/suse/sl-micro/6.0/b
aremetal-os-container:2.1.2-10.4
      elemental.cattle.io/os.name: SL-Micro
      elemental.cattle.io/os.pretty-name: SUSE Linux Micro 6.0
      elemental.cattle.io/os.version: "6.0"
      elemental.cattle.io/os.version-id: "6.0"
      elemental.cattle.io/reg-version: 1.6.3
      elemental.cattle.io/registration-ip: 172.21.8.235
    creationTimestamp: "2024-08-06T09:37:07Z"
[...]
```

Sections that would deserve a rework/integration:
https://elemental.docs.rancher.com/inventory-management/#machineregistration
https://elemental.docs.rancher.com/upgrade-lifecycle/#verifying-successful-upgrades
